name: Main CI

on:
  push:
    branches:
      - master
      - branch-0.6  
  pull_request:

jobs:
  java:
    name: Scala/sbt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
    - name: Cache local sbt repository
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Build with sbt
      run: sbt test publishM2
      env:
        GITHUB_TOKEN: ${{ github.token }} 
