name: Main CI

on:
  push:
    branches:
      - master
      - branch-0.6  

jobs:
  java:
    name: Scala/sbt
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: olafurpg/setup-scala@v5
    - name: Cache local sbt repository
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Build with sbt
      run: sbt test publishM2
      env:
        GITHUB_TOKEN: ${{ github.token }} 
    - name: Push with maven
      run: |
        export VERSION=`cat version.sbt|awk '{print $5}'|sed 's/"//g'`
        # maven doesn't like pushing from local repository so we copy before pushing
        cp /home/runner/.m2/repository/io/delta/delta-core_2.12/$VERSION/delta-core_2.12-$VERSION.* .
        mvn -B deploy:deploy-file -DpomFile=delta-core_2.12-$VERSION.pom -DrepositoryId=github -Dfile=delta-core_2.12-$VERSION.jar -Durl=https://maven.pkg.github.com/projectnessie/delta
      env:
        GITHUB_TOKEN: ${{ github.token }} 

